import { Translations } from "./types";

// ─────────────────────────────────────────────────────────────────
// ⚠ GÜVENLIK: Anahtarlar .env / .env.local dosyasından okunur.
// Üretim ortamında VITE_SUPABASE_URL ve VITE_SUPABASE_ANON_KEY
// mutlaka set edilmelidir. Hardcode fallback KULLANILMAZ.
// ─────────────────────────────────────────────────────────────────
const _supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string;
const _supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

if (!_supabaseUrl || !_supabaseKey) {
  console.error(
    "[FikoAI] VITE_SUPABASE_URL ve/veya VITE_SUPABASE_ANON_KEY ortam değişkenleri bulunamadı.\n" +
    "Lütfen .env dosyanızı kontrol edin."
  );
}

export const SUPABASE_URL: string = _supabaseUrl || "";
export const SUPABASE_ANON_KEY: string = _supabaseKey || "";

export const translations: Record<'tr' | 'de', Translations> = {
  tr: {
    appTitle: "Almanya Ön Muhasebe Sistemi",
    login: "Giriş Yap",
    register: "Kayıt Ol",
    email: "E-posta",
    password: "Şifre",
    loginWithGoogle: "Google ile Giriş Yap",
    orDivider: "veya",
    welcomeTitle: "Almanya Ön Muhasebe Sistemine Hoş Geldiniz",
    welcomeDesc: "İşletmenizi profesyonelce yönetin",
    noAccount: "Hesabınız yok mu?",
    hasAccount: "Zaten hesabınız var mı?",
    logout: "Çıkış",
    dashboard: "Panel",
    accountPlans: "Hesap Planları",
    companies: "Şirketler",
    reports: "Raporlar",
    forms: "Formlar",
    bankDocuments: "Banka Dökümanı",
    maliMusavir: "Mali Müşavir",
    settings: "Ayarlar",
    search: "Ara...",
    id: "ID",
    guvPosten: "GuV Posten",
    programmverbindung: "Program Bağlantısı",
    accountPrefix: "Hesap Öneki",
    accountCode: "Hesap Kodu",
    accountDescription: "Açıklama",
    category: "Kategori",
    balanceItem: "Bilanço Kalemi",
    detailCard: "Detay Kartı",
    selectRow: "Detayları görmek için bir satır seçin",
    totalRows: "Toplam Kayıt",
    loading: "Yükleniyor...",
    loginError: "Giriş başarısız",
    registerSuccess: "Kayıt başarılı! E-postanızı kontrol edin.",
    registerError: "Kayıt başarısız",
    analysisJustification: "Analiz Gerekçesi",
    createdAt: "Oluşturma Tarihi",
    language: "Dil",
    profile: "Profil",
    admin: "Yönetici",
    user: "Kullanıcı",
    analyzeWithAI: "Yapay Zeka ile Analiz Et",
    aiThinking: "Yapay Zeka Düşünüyor...",
    aiAnalysisResult: "AI Analiz Sonucu",
    uploadInvoice: "Fatura Yükle (Görsel)",
    analyzeInvoice: "Faturayı Analiz Et",
    generateCover: "Rapor Kapağı Oluştur",
    aspectRatio: "En Boy Oranı",
    generate: "Oluştur",
    companyInfo: "Şirket Bilgileri",
    companyName: "Şirket Adı",
    taxNumber: "Vergi Numarası",
    address: "Adres",
    city: "Şehir",
    phone: "Telefon",
    companyEmail: "Şirket E-posta",
    userEmail: "Kullanıcı (E-posta)",
    save: "Kaydet",
    edit: "Düzenle",
    cancel: "İptal",
    saved: "Kaydedildi!",
    companyRequired: "Şirket adı zorunludur",
    noCompanies: "Henüz kayıtlı şirket yok",
    companyDetail: "Şirket Detayı",
    selectCompany: "Detay görmek için bir kayıt seçin",
    deleteCompany: "Kaydı Sil",
    deleteConfirm: "Bu kaydı silmek istediğinize emin misiniz?",
    deleted: "Silindi!",
    subscription: "Abonelik",
    invoices: "Faturalar",
  },
  de: {
    appTitle: "Deutschland Vorbuchhaltungssystem",
    login: "Anmelden",
    register: "Registrieren",
    email: "E-Mail",
    password: "Passwort",
    loginWithGoogle: "Mit Google anmelden",
    orDivider: "oder",
    welcomeTitle: "Willkommen beim Vorbuchhaltungssystem",
    welcomeDesc: "Verwalten Sie Ihr Unternehmen professionell",
    noAccount: "Kein Konto?",
    hasAccount: "Bereits ein Konto?",
    logout: "Abmelden",
    dashboard: "Dashboard",
    accountPlans: "Kontenplan",
    companies: "Unternehmen",
    reports: "Berichte",
    forms: "Formulare",
    bankDocuments: "Bankdokumente",
    maliMusavir: "Steuerberater",
    settings: "Einstellungen",
    search: "Suchen...",
    id: "ID",
    guvPosten: "GuV Posten",
    programmverbindung: "Programmverbindung",
    accountPrefix: "Kontenpräfix",
    accountCode: "Kontencode",
    accountDescription: "Beschreibung",
    category: "Kategorie",
    balanceItem: "Bilanzposten",
    detailCard: "Detailkarte",
    selectRow: "Wählen Sie eine Zeile für Details",
    totalRows: "Gesamteinträge",
    loading: "Laden...",
    loginError: "Anmeldung fehlgeschlagen",
    registerSuccess: "Registrierung erfolgreich! Überprüfen Sie Ihre E-Mail.",
    registerError: "Registrierung fehlgeschlagen",
    analysisJustification: "Analysebegründung",
    createdAt: "Erstellt am",
    language: "Sprache",
    profile: "Profil",
    admin: "Administrator",
    user: "Benutzer",
    analyzeWithAI: "Mit KI analysieren",
    aiThinking: "KI denkt nach...",
    aiAnalysisResult: "KI-Analyseergebnis",
    uploadInvoice: "Rechnung hochladen (Bild)",
    analyzeInvoice: "Rechnung analysieren",
    generateCover: "Berichtsdeckblatt erstellen",
    aspectRatio: "Seitenverhältnis",
    generate: "Generieren",
    companyInfo: "Unternehmensdaten",
    companyName: "Firmenname",
    taxNumber: "Steuernummer",
    address: "Adresse",
    city: "Stadt",
    phone: "Telefon",
    companyEmail: "Firmen-E-Mail",
    userEmail: "Benutzer (E-Mail)",
    save: "Speichern",
    edit: "Bearbeiten",
    cancel: "Abbrechen",
    saved: "Gespeichert!",
    companyRequired: "Firmenname ist erforderlich",
    noCompanies: "Noch keine Unternehmen registriert",
    companyDetail: "Firmendetail",
    selectCompany: "Wählen Sie einen Datensatz",
    deleteCompany: "Datensatz löschen",
    deleteConfirm: "Möchten Sie diesen Datensatz wirklich löschen?",
    deleted: "Gelöscht!",
    subscription: "Abonnement",
    invoices: "Rechnungen",
  },
};
